### ISSUE TITLE
Incorrect shortcuts for zooming in/scalingup

### ISSUE THREAD

**Issue by geladariia** [anytypeio/community-board#42]
<h4>
<a name="what-is-the-bug-1" class="anchor" href="#what-is-the-bug-1"></a>WHAT IS THE BUG</h4>
<p>Scaling is working but shortcuts are incorrect:</p>
<p><img src="https://community-content.anytype.io/original/2X/3/38adf971d790aa03e9cabc1a3f759a33b73c9977.png" alt="image" data-base62-sha1="85ptyGayr4OKN5fDP1kzPGGF5VZ" width="386" height="175"></p>
<p>Zooming in only works for me with CTRL + SHIFT + “+”.</p>
<h4>
<a name="how-to-reproduce-it-2" class="anchor" href="#how-to-reproduce-it-2"></a>HOW TO REPRODUCE IT</h4>
<ol>
<li>Open Anytype</li>
<li>Use CTRL + “-” to scale down (make smaller)</li>
<li>Try to use CTRL + “+” to scale up (make bigger) and see it doesn’t work</li>
<li>User CTRL + SHIFT + “+” to scale up and see it works</li>
</ol>
<h4>
<a name="the-expected-behavior-3" class="anchor" href="#the-expected-behavior-3"></a>THE EXPECTED BEHAVIOR</h4>
<p>The shortcuts should be as described in the keyboard shortcut guide in Anytype.</p>
<h4>
<a name="system-informations-4" class="anchor" href="#system-informations-4"></a>SYSTEM INFORMATIONS</h4>
<ul>
<li>
<strong>OS:</strong><br>
Windows 11</li>
<li>
<strong>Device:</strong><br>
Dell XPS 15</li>
<li>
<strong>Anytype Version:</strong><br>
0.27.26-beta</li>
</ul>
<h4>
<a name="additional-context-5" class="anchor" href="#additional-context-5"></a>ADDITIONAL CONTEXT</h4>
<p>Check out my post on terminology to see “scaling” vs “zooming”</p>
<aside class="quote quote-modified" data-post="1" data-topic="5812">
  <div class="title">
    <div class="quote-controls"></div>
    <img loading="lazy" alt="" width="20" height="20" src="https://community.anytype.io/user_avatar/community.anytype.io/sambouwer/40/3042_2.png" class="avatar">
    <a href="https://community.anytype.io/t/terminology-and-concepts/5812">Terminology and Concepts</a> <a class="badge-wrapper  box" href="/c/general-discussion/10"><span class="badge-category-bg" style="background-color: #9a9ecb;"></span><span style="color: #FFF" data-drop-close="true" class="badge-category clear-badge" title="Chat about all things related to Anytype that don’t fit into another category. Or head into the Lounge for truly “off-topic” discussions.">General Discussion</span></a>
  </div>
  <blockquote>
    I notice there are some misunderstandings and disagreements on certain terms used across many topics. I hope we can clarify some common terminology that might be ambiguous. What I’m writing here is not necessarily the right answer, this is just to get the conversation started. Feel free to suggest your own additions to this list as it is not complete. 
Anytype specific 

Object 
A container for Blocks. Not to be confused with a Block itself. All Blocks are (or should be) an Object. Not all Objec…
  </blockquote>
</aside>

watch topic: https://community.anytype.io/t/7258

**Comment by SamBouwer** [comment]
@geladariia this topic can be closed here. The issue is resolved.
