### ISSUE TITLE
Indicator for zoom

### ISSUE THREAD

**Issue by geladariia** [anytypeio/community-board#45]
<p>As talked about with <a class="mention" href="/u/razor">@Razor</a> on slack.<br>
Here the request for an indicator of the current zoom level like in browsers.<br>
<img src="https://community-content.anytype.io/original/2X/5/50687e54b69a521eb528c612868753ad69d897ba.png" alt="image" data-base62-sha1="btk4A0LnvgGbWcQpAaDYWRXr3oC" width="282" height="83"></p>
<p>With the option to click it, to get back to 100%.</p>

watch topic: https://community.anytype.io/t/7239

**Comment by SamBouwer** [comment]
Can be closed here, will be tracked in Linear
